do $$
begin
  if not exists (select 1 from pg_type where typname = 'jobstatus') then
    create type jobstatus as enum ('queued', 'processing', 'completed', 'failed', 'cancelled');
  end if;
end $$;

create table if not exists public.profiles (
  id text primary key,
  email text,
  work_email text,
  first_name text,
  last_name text,
  company_name text,
  role text default 'user',
  signup_ip text,
  last_ip text,
  last_seen_at timestamptz,
  created_at timestamptz default now()
);

alter table public.profiles add column if not exists work_email text;
alter table public.profiles add column if not exists first_name text;
alter table public.profiles add column if not exists last_name text;
alter table public.profiles add column if not exists company_name text;
alter table public.profiles add column if not exists role text;
alter table public.profiles add column if not exists signup_ip text;
alter table public.profiles add column if not exists last_ip text;
alter table public.profiles add column if not exists last_seen_at timestamptz;
alter table public.profiles add column if not exists created_at timestamptz;

create index if not exists ix_profiles_id on public.profiles (id);
create index if not exists ix_profiles_email on public.profiles (email);
create index if not exists ix_profiles_work_email on public.profiles (work_email);
create index if not exists ix_profiles_role on public.profiles (role);

create table if not exists public.subscriptions (
  id integer generated by default as identity primary key,
  user_id text unique,
  plan_key text,
  status text,
  current_period_end timestamptz,
  provider text,
  provider_customer_id text,
  provider_subscription_id text,
  provider_order_id text,
  stripe_customer_id text,
  stripe_subscription_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.subscriptions add column if not exists user_id text;
alter table public.subscriptions add column if not exists plan_key text;
alter table public.subscriptions add column if not exists status text;
alter table public.subscriptions add column if not exists current_period_end timestamptz;
alter table public.subscriptions add column if not exists provider text;
alter table public.subscriptions add column if not exists provider_customer_id text;
alter table public.subscriptions add column if not exists provider_subscription_id text;
alter table public.subscriptions add column if not exists provider_order_id text;
alter table public.subscriptions add column if not exists stripe_customer_id text;
alter table public.subscriptions add column if not exists stripe_subscription_id text;
alter table public.subscriptions add column if not exists created_at timestamptz;
alter table public.subscriptions add column if not exists updated_at timestamptz;

create index if not exists ix_subscriptions_id on public.subscriptions (id);
create unique index if not exists ix_subscriptions_user_id on public.subscriptions (user_id);
create index if not exists ix_subscriptions_plan_key on public.subscriptions (plan_key);
create index if not exists ix_subscriptions_status on public.subscriptions (status);
create index if not exists ix_subscriptions_provider on public.subscriptions (provider);
create index if not exists ix_subscriptions_provider_customer_id on public.subscriptions (provider_customer_id);
create index if not exists ix_subscriptions_provider_subscription_id on public.subscriptions (provider_subscription_id);
create index if not exists ix_subscriptions_provider_order_id on public.subscriptions (provider_order_id);

create table if not exists public.credit_accounts (
  user_id text primary key,
  balance integer default 0,
  updated_at timestamptz default now()
);

alter table public.credit_accounts add column if not exists balance integer;
alter table public.credit_accounts add column if not exists updated_at timestamptz;

create index if not exists ix_credit_accounts_user_id on public.credit_accounts (user_id);

create table if not exists public.credit_ledger (
  id integer generated by default as identity primary key,
  user_id text,
  lot_id text,
  event_type text,
  delta integer,
  source text,
  job_id integer,
  created_at timestamptz default now(),
  expires_at timestamptz,
  metadata jsonb
);

alter table public.credit_ledger add column if not exists user_id text;
alter table public.credit_ledger add column if not exists lot_id text;
alter table public.credit_ledger add column if not exists event_type text;
alter table public.credit_ledger add column if not exists delta integer;
alter table public.credit_ledger add column if not exists source text;
alter table public.credit_ledger add column if not exists job_id integer;
alter table public.credit_ledger add column if not exists created_at timestamptz;
alter table public.credit_ledger add column if not exists expires_at timestamptz;
alter table public.credit_ledger add column if not exists metadata jsonb;

create index if not exists ix_credit_ledger_id on public.credit_ledger (id);
create index if not exists ix_credit_ledger_user_id on public.credit_ledger (user_id);
create index if not exists ix_credit_ledger_lot_id on public.credit_ledger (lot_id);
create index if not exists ix_credit_ledger_event_type on public.credit_ledger (event_type);
create index if not exists ix_credit_ledger_source on public.credit_ledger (source);
create index if not exists ix_credit_ledger_job_id on public.credit_ledger (job_id);
create index if not exists ix_credit_ledger_expires_at on public.credit_ledger (expires_at);

create table if not exists public.jobs (
  id integer generated by default as identity primary key,
  user_id text,
  support_id text,
  filename text,
  status jobstatus default 'queued',
  total_companies integer default 0,
  processed_companies integer default 0,
  decision_makers_found integer default 0,
  llm_calls_started integer default 0,
  llm_calls_succeeded integer default 0,
  serper_calls integer default 0,
  llm_prompt_tokens integer default 0,
  llm_completion_tokens integer default 0,
  llm_total_tokens integer default 0,
  llm_cost_usd double precision default 0,
  serper_cost_usd double precision default 0,
  total_cost_usd double precision default 0,
  cost_per_contact_usd double precision default 0,
  column_mappings jsonb,
  companies_data jsonb,
  selected_platforms jsonb,
  max_contacts_total integer default 50,
  max_contacts_per_company integer default 1,
  credits_spent integer default 0,
  stop_reason text,
  options jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz
);

alter table public.jobs add column if not exists user_id text;
alter table public.jobs add column if not exists support_id text;
alter table public.jobs add column if not exists filename text;
alter table public.jobs add column if not exists status jobstatus;
alter table public.jobs add column if not exists total_companies integer;
alter table public.jobs add column if not exists processed_companies integer;
alter table public.jobs add column if not exists decision_makers_found integer;
alter table public.jobs add column if not exists llm_calls_started integer;
alter table public.jobs add column if not exists llm_calls_succeeded integer;
alter table public.jobs add column if not exists serper_calls integer;
alter table public.jobs add column if not exists llm_prompt_tokens integer;
alter table public.jobs add column if not exists llm_completion_tokens integer;
alter table public.jobs add column if not exists llm_total_tokens integer;
alter table public.jobs add column if not exists llm_cost_usd double precision;
alter table public.jobs add column if not exists serper_cost_usd double precision;
alter table public.jobs add column if not exists total_cost_usd double precision;
alter table public.jobs add column if not exists cost_per_contact_usd double precision;
alter table public.jobs add column if not exists column_mappings jsonb;
alter table public.jobs add column if not exists companies_data jsonb;
alter table public.jobs add column if not exists selected_platforms jsonb;
alter table public.jobs add column if not exists max_contacts_total integer;
alter table public.jobs add column if not exists max_contacts_per_company integer;
alter table public.jobs add column if not exists credits_spent integer;
alter table public.jobs add column if not exists stop_reason text;
alter table public.jobs add column if not exists options jsonb;
alter table public.jobs add column if not exists created_at timestamptz;
alter table public.jobs add column if not exists updated_at timestamptz;

create index if not exists ix_jobs_id on public.jobs (id);
create index if not exists ix_jobs_user_id on public.jobs (user_id);
create index if not exists ix_jobs_support_id on public.jobs (support_id);
create index if not exists ix_jobs_filename on public.jobs (filename);
create index if not exists ix_jobs_status on public.jobs (status);
create index if not exists ix_jobs_created_at on public.jobs (created_at);

create table if not exists public.decision_makers (
  id integer generated by default as identity primary key,
  user_id text,
  job_id integer,
  company_name text,
  company_type text,
  company_city text,
  company_country text,
  company_website text,
  company_address text,
  gmaps_rating double precision,
  gmaps_reviews integer,
  name text,
  title text,
  platform text,
  profile_url text,
  confidence_score text,
  reasoning text,
  uploaded_company_data text,
  llm_input text,
  serper_queries text,
  llm_output text,
  llm_call_timestamp timestamptz,
  serper_call_timestamp timestamptz,
  emails_found text
);

alter table public.decision_makers add column if not exists user_id text;
alter table public.decision_makers add column if not exists job_id integer;
alter table public.decision_makers add column if not exists company_name text;
alter table public.decision_makers add column if not exists company_type text;
alter table public.decision_makers add column if not exists company_city text;
alter table public.decision_makers add column if not exists company_country text;
alter table public.decision_makers add column if not exists company_website text;
alter table public.decision_makers add column if not exists company_address text;
alter table public.decision_makers add column if not exists gmaps_rating double precision;
alter table public.decision_makers add column if not exists gmaps_reviews integer;
alter table public.decision_makers add column if not exists name text;
alter table public.decision_makers add column if not exists title text;
alter table public.decision_makers add column if not exists platform text;
alter table public.decision_makers add column if not exists profile_url text;
alter table public.decision_makers add column if not exists confidence_score text;
alter table public.decision_makers add column if not exists reasoning text;
alter table public.decision_makers add column if not exists uploaded_company_data text;
alter table public.decision_makers add column if not exists llm_input text;
alter table public.decision_makers add column if not exists serper_queries text;
alter table public.decision_makers add column if not exists llm_output text;
alter table public.decision_makers add column if not exists llm_call_timestamp timestamptz;
alter table public.decision_makers add column if not exists serper_call_timestamp timestamptz;
alter table public.decision_makers add column if not exists emails_found text;

create index if not exists ix_decision_makers_id on public.decision_makers (id);
create index if not exists ix_decision_makers_user_id on public.decision_makers (user_id);
create index if not exists ix_decision_makers_job_id on public.decision_makers (job_id);
create index if not exists ix_decision_makers_company_name on public.decision_makers (company_name);

create table if not exists public.coupon_codes (
  id integer generated by default as identity primary key,
  code text unique,
  coupon_type text,
  active integer default 1,
  metadata jsonb,
  created_at timestamptz default now()
);

alter table public.coupon_codes add column if not exists code text;
alter table public.coupon_codes add column if not exists coupon_type text;
alter table public.coupon_codes add column if not exists active integer;
alter table public.coupon_codes add column if not exists metadata jsonb;
alter table public.coupon_codes add column if not exists created_at timestamptz;

create index if not exists ix_coupon_codes_id on public.coupon_codes (id);
create unique index if not exists ix_coupon_codes_code on public.coupon_codes (code);
create index if not exists ix_coupon_codes_coupon_type on public.coupon_codes (coupon_type);

create table if not exists public.coupon_assignments (
  id integer generated by default as identity primary key,
  coupon_code_id integer,
  user_id text,
  created_at timestamptz default now(),
  redeemed_at timestamptz
);

alter table public.coupon_assignments add column if not exists coupon_code_id integer;
alter table public.coupon_assignments add column if not exists user_id text;
alter table public.coupon_assignments add column if not exists created_at timestamptz;
alter table public.coupon_assignments add column if not exists redeemed_at timestamptz;

create index if not exists ix_coupon_assignments_id on public.coupon_assignments (id);
create index if not exists ix_coupon_assignments_coupon_code_id on public.coupon_assignments (coupon_code_id);
create index if not exists ix_coupon_assignments_user_id on public.coupon_assignments (user_id);

create table if not exists public.support_conversations (
  id integer generated by default as identity primary key,
  user_id text,
  status text default 'open',
  created_at timestamptz default now()
);

alter table public.support_conversations add column if not exists user_id text;
alter table public.support_conversations add column if not exists status text;
alter table public.support_conversations add column if not exists created_at timestamptz;

create index if not exists ix_support_conversations_id on public.support_conversations (id);
create index if not exists ix_support_conversations_user_id on public.support_conversations (user_id);
create index if not exists ix_support_conversations_status on public.support_conversations (status);

create table if not exists public.support_messages (
  id integer generated by default as identity primary key,
  conversation_id integer,
  sender_role text,
  content text,
  created_at timestamptz default now()
);

alter table public.support_messages add column if not exists conversation_id integer;
alter table public.support_messages add column if not exists sender_role text;
alter table public.support_messages add column if not exists content text;
alter table public.support_messages add column if not exists created_at timestamptz;

create index if not exists ix_support_messages_id on public.support_messages (id);
create index if not exists ix_support_messages_conversation_id on public.support_messages (conversation_id);
create index if not exists ix_support_messages_sender_role on public.support_messages (sender_role);

create table if not exists public.credit_state (
  id integer primary key,
  balance integer default 0
);

alter table public.credit_state add column if not exists balance integer;

